package com.buddy;

import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.scene.paint.Color;
import javafx.stage.Stage;
import javafx.scene.text.Font;
import javafx.scene.text.FontWeight;
import javafx.scene.text.Text; 

import java.io.IOException;

/**
 * JavaFX App
 */
public class App extends Application {

    private static Scene scene;

    @Override
    public void start(Stage primaryStage) {
        primaryStage.setTitle("JavaFX Welcome");
        GridPane grid = new GridPane();
        grid.setAlignment(Pos.CENTER);
        grid.setHgap(10);
        grid.setVgap(10);
        grid.setPadding(new Insets(25, 25, 25, 25));

        // Creates Top title
        Text scenetitle = new Text("Welcome");
        // Need to set font to avoid gibberish (Mac Issue?)
        scenetitle.setFont(Font.font("Tahoma", FontWeight.NORMAL, 20));
        grid.add(scenetitle, 0, 0, 2, 1);
        
        // TODO - Loop geneates all the labels, textboxs, and out puts needed

        // Creates label
        Label userName = new Label("User Name:");
        userName.setFont(Font.font("Tahoma", FontWeight.NORMAL, 12));
        grid.add(userName, 0, 1);

        // Creates text box for user to input into 
        TextField userTextField = new TextField();
        userTextField.setFont(Font.font("Tahoma", FontWeight.NORMAL, 12));
        grid.add(userTextField, 1, 1);

        // Button creations
        Button btn = new Button("Generate Job Cost");
        HBox hbBtn = new HBox(10);
        hbBtn.setAlignment(Pos.BOTTOM_RIGHT);
        hbBtn.getChildren().add(btn);
        btn.setFont(Font.font("Tahoma", FontWeight.NORMAL, 12));
        grid.add(hbBtn, 1, 4);

        // Text control
        final Text actiontarget = new Text();
        grid.add(actiontarget, 1, 6);

        // Event when button is hit, this is where the job cost will be generated
        btn.setOnAction((EventHandler<ActionEvent>) new EventHandler<ActionEvent>() {
            @Override
            public void handle(ActionEvent e) {
                // Generates text to display once button is clicked 
                actiontarget.setFill(Color.FIREBRICK);
                actiontarget.setFont(Font.font("Tahoma", FontWeight.NORMAL, 12));
                // Gets the inputed data
                String tmp = userTextField.getText();
                System.out.println(tmp);
                actiontarget.setText(tmp);
             
            }
        });

        // Generates the scene (pop-up window)
        Scene scene = new Scene(grid, 300, 275);
        primaryStage.setScene(scene);
        primaryStage.show();
    }


        


    // Autogenerated below, does stuff to run, forsure does smth yup
    static void setRoot(String fxml) throws IOException {
        scene.setRoot(loadFXML(fxml));
    }

    private static Parent loadFXML(String fxml) throws IOException {
        FXMLLoader fxmlLoader = new FXMLLoader(App.class.getResource(fxml + ".fxml"));
        return fxmlLoader.load();
    }

    public static void main(String[] args) {
        launch();
    }


}

